spring.application.name=expense-tracker-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
#  Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-version=0

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS (под фронтенд Vite на 5173 порту)
app.client-url=${CLIENT_URL:http://localhost:5173}


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# JWT
app.jwt.secret=super-long-secret-key-1234567890-ABCDEFG
# 7 days 
app.jwt.expiration-ms=604800000

# Файлы
app.upload.dir=uploads

spring.servlet.multipart.enabled=true

server.port=5001

# Redis (cache)
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000
spring.cache.redis.cache-null-values=false

# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Debug логов для проверки
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=DEBUG