spring.application.name=expense-tracker-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS (под фронтенд Vite на 5173 порту)
app.client-url=${CLIENT_URL:http://localhost:5173}


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# JWT
app.jwt.secret=super-long-secret-key-1234567890-ABCDEFG
# 7 days (dev-friendly; reduce for production)
app.jwt.expiration-ms=604800000

# Файлы
app.upload.dir=uploads

spring.servlet.multipart.enabled=true

server.port=5001

# Redis (cache)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=none

